### ISSUE TITLE
MASIA code problem in momentum_update function

### ISSUE THREAD

**Issue by limeorange89** [chenf-ai/Multi-Agent-Communication-Considering-Representation-Learning#1]
Hello. I am researching MARL communication, and I am very interested in your MASIA algorithm. I tried simulation using the code you posted here, but there was a problem, so I'd like to ask for your help.
Simulations using other algorithms (full_comm, qmix) work well, but only MASIA causes the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sacred/experiment.py", line 312, in run_commandline
    return self.run(
  File "/usr/local/lib/python3.8/dist-packages/sacred/experiment.py", line 276, in run
    run()
  File "/usr/local/lib/python3.8/dist-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/usr/local/lib/python3.8/dist-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "src/main.py", line 40, in my_main
    msra_run(_run, config, _log)
  File "/home/devi/MASIA/src/msra_run.py", line 130, in msra_run
    run_sequential(args=args, logger=logger)
  File "/home/devi/MASIA/src/msra_run.py", line 319, in run_sequential
    learner.train(episode_sample, runner.t_env, episode)
  File "/home/devi/MASIA/src/learners/masia_learner.py", line 249, in train
    self.rl_train(batch, t_env, episode_num, repr_loss)
  File "/home/devi/MASIA/src/learners/masia_learner.py", line 229, in rl_train
    self.mac.agent.momentum_update()
  File "/home/devi/MASIA/src/modules/agents/masia_agent.py", line 256, in momentum_update
    update_state_dict(self.target_encoder, self.encoder, self.args.momentum_tau)
AttributeError: 'types.SimpleNamespace' object has no attribute 'momentum_tau'
```
As you can see, an error occurred due to the momentum_tau value. So, to solve this problem, I enter the initial momentum_tau value of 1 in the masia.yaml file.
However, after that, an error occurs in the ```model.load_state_dict(state_dict)``` as shown below.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sacred/experiment.py", line 312, in run_commandline
    return self.run(
  File "/usr/local/lib/python3.8/dist-packages/sacred/experiment.py", line 276, in run
    run()
  File "/usr/local/lib/python3.8/dist-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/usr/local/lib/python3.8/dist-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "src/main.py", line 40, in my_main
    msra_run(_run, config, _log)
  File "/home/devi/MASIA/src/msra_run.py", line 130, in msra_run
    run_sequential(args=args, logger=logger)
  File "/home/devi/MASIA/src/msra_run.py", line 319, in run_sequential
    learner.train(episode_sample, runner.t_env, episode)
  File "/home/devi/MASIA/src/learners/masia_learner.py", line 249, in train
    self.rl_train(batch, t_env, episode_num, repr_loss)
  File "/home/devi/MASIA/src/learners/masia_learner.py", line 229, in rl_train
    self.mac.agent.momentum_update()
  File "/home/devi/MASIA/src/modules/agents/masia_agent.py", line 256, in momentum_update
    update_state_dict(self.target_encoder, self.encoder, self.args.momentum_tau)
  File "/home/devi/MASIA/src/modules/agents/masia_agent.py", line 251, in update_state_dict
    model.load_state_dict(state_dict)
  File "/home/devi/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1470, in load_state_dict
    state_dict = state_dict.copy()
  File "/home/devi/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ObAttnAEEnc' object has no attribute 'copy'
```
Is there a fix for this? I'll be waiting for your reply. Thanks!

**Comment by chenf-ai** [comment]
> Hello. I am researching MARL communication, and I am very interested in your MASIA algorithm. I tried simulation using the code you posted here, but there was a problem, so I'd like to ask for your help. Simulations using other algorithms (full_comm, qmix) work well, but only MASIA causes the following error:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/sacred/experiment.py", line 312, in run_commandline
>     return self.run(
>   File "/usr/local/lib/python3.8/dist-packages/sacred/experiment.py", line 276, in run
>     run()
>   File "/usr/local/lib/python3.8/dist-packages/sacred/run.py", line 238, in __call__
>     self.result = self.main_function(*args)
>   File "/usr/local/lib/python3.8/dist-packages/sacred/config/captured_function.py", line 42, in captured_function
>     result = wrapped(*args, **kwargs)
>   File "src/main.py", line 40, in my_main
>     msra_run(_run, config, _log)
>   File "/home/devi/MASIA/src/msra_run.py", line 130, in msra_run
>     run_sequential(args=args, logger=logger)
>   File "/home/devi/MASIA/src/msra_run.py", line 319, in run_sequential
>     learner.train(episode_sample, runner.t_env, episode)
>   File "/home/devi/MASIA/src/learners/masia_learner.py", line 249, in train
>     self.rl_train(batch, t_env, episode_num, repr_loss)
>   File "/home/devi/MASIA/src/learners/masia_learner.py", line 229, in rl_train
>     self.mac.agent.momentum_update()
>   File "/home/devi/MASIA/src/modules/agents/masia_agent.py", line 256, in momentum_update
>     update_state_dict(self.target_encoder, self.encoder, self.args.momentum_tau)
> AttributeError: 'types.SimpleNamespace' object has no attribute 'momentum_tau'
> ```
> 
> As you can see, an error occurred due to the momentum_tau value. So, to solve this problem, I enter the initial momentum_tau value of 1 in the masia.yaml file. However, after that, an error occurs in the `model.load_state_dict(state_dict)` as shown below.
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/sacred/experiment.py", line 312, in run_commandline
>     return self.run(
>   File "/usr/local/lib/python3.8/dist-packages/sacred/experiment.py", line 276, in run
>     run()
>   File "/usr/local/lib/python3.8/dist-packages/sacred/run.py", line 238, in __call__
>     self.result = self.main_function(*args)
>   File "/usr/local/lib/python3.8/dist-packages/sacred/config/captured_function.py", line 42, in captured_function
>     result = wrapped(*args, **kwargs)
>   File "src/main.py", line 40, in my_main
>     msra_run(_run, config, _log)
>   File "/home/devi/MASIA/src/msra_run.py", line 130, in msra_run
>     run_sequential(args=args, logger=logger)
>   File "/home/devi/MASIA/src/msra_run.py", line 319, in run_sequential
>     learner.train(episode_sample, runner.t_env, episode)
>   File "/home/devi/MASIA/src/learners/masia_learner.py", line 249, in train
>     self.rl_train(batch, t_env, episode_num, repr_loss)
>   File "/home/devi/MASIA/src/learners/masia_learner.py", line 229, in rl_train
>     self.mac.agent.momentum_update()
>   File "/home/devi/MASIA/src/modules/agents/masia_agent.py", line 256, in momentum_update
>     update_state_dict(self.target_encoder, self.encoder, self.args.momentum_tau)
>   File "/home/devi/MASIA/src/modules/agents/masia_agent.py", line 251, in update_state_dict
>     model.load_state_dict(state_dict)
>   File "/home/devi/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1470, in load_state_dict
>     state_dict = state_dict.copy()
>   File "/home/devi/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
>     raise AttributeError("'{}' object has no attribute '{}'".format(
> AttributeError: 'ObAttnAEEnc' object has no attribute 'copy'
> ```
> 
> Is there a fix for this? I'll be waiting for your reply. Thanks!

I am glad that you are interested in our work, and I appreciate your time looking into it and proposing this issue! It results in that there is a little mistake in the posted version of the code, where the arg passed in should be `nn.module.state_dict()` instead of `nn.module`. I have solved this issue and updated the repo. Now you can feel free to try again!

Actually, I was in the middle of various tasks and found it hard to get away in the last two months. I’m going to organize the various branches of this project and sort out the official version, where more detailed instructions will be offered. I hope to finish this work at the start of January. Thanks again for your question, and more comments are always welcome if you have some other problems : )

**Comment by limeorange89** [comment]
Simulated with updated code. And I checked that it works well. I'll look forward to the official version. Thank you!
